name: Login Tests

on:
  push:
    branches: [ master, main ]
    paths:
      - 'login_tests/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'login_tests/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: login_tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Install Google Chrome
        run: |
          echo "Installing Google Chrome..."
          sudo apt-get update
          sudo apt-get install -y wget curl gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Set CHROME_BIN environment variable
        run: echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV

      - name: Build and test with Maven with enhanced logging
        run: |
          echo "Running Maven tests..."
          export SELENIUM_LOG_LEVEL=DEBUG
          mvn clean test -Dorg.slf4j.simpleLogger.defaultLogLevel=debug \
          -Dadmin.username='${{ secrets.ADMIN_USERNAME }}' \
          -Dadmin.password='${{ secrets.ADMIN_PASSWORD }}' \
          -Dbase.url='${{ secrets.BASE_URL }}'
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: target/surefire-reports

      - name: Upload screenshots if available
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: |
            **/screenshots
            **/error-screenshots
            **/logs
