name: Login Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.java'
      - '.github/workflows/login_test.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      # Додамо перевірку доступності сервера
      - name: Check if server is reachable
        run: |
          # Використовуємо curl для перевірки доступності сервера
          # Використовуємо сервер без шляху, щоб отримати головну сторінку
          SERVER_URL="${{ secrets.BASE_URL }}"
          echo "Checking server availability at: $SERVER_URL"
          curl -I -L --max-time 30 "$SERVER_URL" || echo "Server might be unreachable or slow"

      - name: Build and test with Maven with enhanced logging
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          export SELENIUM_LOG_LEVEL=DEBUG
          mvn clean test -Dorg.slf4j.simpleLogger.defaultLogLevel=debug \
          -Dadmin.username='${{ secrets.ADMIN_USERNAME }}' \
          -Dadmin.password='${{ secrets.ADMIN_PASSWORD }}' \
          -Dbase.url='${{ secrets.BASE_URL }}'
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: target/surefire-reports

      - name: Upload screenshots if available
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: |
            **/screenshots
            **/error-screenshots
            **/logs