name: Automated API tests using Postman CLI

on: 
  push:
    branches:
      - master 

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  

      - name: Install Postman CLI 
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI  # Логін через API ключ
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests  # Запуск тестів Postman
        run: |
          postman collection run "38149766-7a224270-05e2-40f6-98b2-e307abbf37d2"  # Collection ID

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: results/report.json
